class Config:
    def __init__(self):
        self.training_params = {
            'cifar10': {
                'msdnet24_1': {'batch_size': 16,
                               'num_epoch': 5,
                               'lr': 0.1,
                               'lr_type': 'multistep',
                               'decay_rate': 0.1,
                               'decay_epochs': [100, 200],
                               'weight_decay': 4e-4,
                               'momentum': 0.9,
                               'optimizer': 'sgd'},
                'msdnet24_4': {'batch_size': 16,
                               'num_epoch': 5,
                               'lr': 0.1,
                               'lr_type': 'multistep',
                               'decay_rate': 0.1,
                               'decay_epochs': [100, 200],
                               'weight_decay': 4e-4,
                               'momentum': 0.9,
                               'optimizer': 'sgd'},
                'resnet110_1': {'batch_size': 16,
                                'num_epoch': 5,
                                'lr': 0.1,
                                'lr_type': 'multistep',
                                'decay_rate': 0.1,
                                'decay_epochs': [100, 200],
                                'weight_decay': 5e-4,
                                'momentum': 0.9,
                                'optimizer': 'sgd'},
                'resnet110_4': {'batch_size': 16,
                                'num_epoch': 5,
                                'lr': 0.1,
                                'lr_type': 'multistep',
                                'decay_rate': 0.1,
                                'decay_epochs': [100, 200],
                                'weight_decay': 5e-4,
                                'momentum': 0.9,
                                'optimizer': 'sgd'},
                'vgg16_1': {'batch_size': 16,
                            'num_epoch': 5,
                            'lr': 0.1,
                            'lr_type': 'multistep',
                            'decay_rate': 0.1,
                            'decay_epochs': [100, 200],
                            'weight_decay': 5e-4,
                            'momentum': 0.9,
                            'optimizer': 'sgd'},
                'vgg16_4': {'batch_size': 16,
                            'num_epoch': 5,
                            'lr': 0.1,
                            'lr_type': 'multistep',
                            'decay_rate': 0.1,
                            'decay_epochs': [100, 200],
                            'weight_decay': 5e-4,
                            'momentum': 0.9,
                            'optimizer': 'sgd'},
                'mobilenet_v2_1': {'batch_size': 16,
                                   'num_epoch': 5,
                                   'lr': 0.1,
                                   'lr_type': 'multistep',
                                   'decay_rate': 0.1,
                                   'decay_epochs': [100, 200],
                                   'weight_decay': 5e-4,
                                   'momentum': 0.9,
                                   'optimizer': 'sgd'},
                'mobilenet_v2_4': {'batch_size': 16,
                                   'num_epoch': 5,
                                   'lr': 0.1,
                                   'lr_type': 'multistep',
                                   'decay_rate': 0.1,
                                   'decay_epochs': [100, 200],
                                   'weight_decay': 5e-4,
                                   'momentum': 0.9,
                                   'optimizer': 'sgd'}
            },
            'cifar100': {
                'msdnet24_1': {'batch_size': 16,
                               'num_epoch': 5,
                               'lr': 0.1,
                               'lr_type': 'multistep',
                               'decay_rate': 0.1,
                               'decay_epochs': [100, 200],
                               'weight_decay': 5e-4,
                               'momentum': 0.9,
                               'optimizer': 'sgd'},
                'msdnet24_4': {'batch_size': 16,
                               'num_epoch': 5,
                               'lr': 0.1,
                               'lr_type': 'multistep',
                               'decay_rate': 0.1,
                               'decay_epochs': [100, 200],
                               'weight_decay': 5e-4,
                               'momentum': 0.9,
                               'optimizer': 'sgd'},
                'resnet110_1': {'batch_size': 16,
                                'num_epoch': 5,
                                'lr': 0.1,
                                'lr_type': 'multistep',
                                'decay_rate': 0.1,
                                'decay_epochs': [100, 200],
                                'weight_decay': 5e-4,
                                'momentum': 0.9,
                                'optimizer': 'sgd'},
                'resnet110_4': {'batch_size': 16,
                                'num_epoch': 5,
                                'lr': 0.1,
                                'lr_type': 'multistep',
                                'decay_rate': 0.1,
                                'decay_epochs': [100, 200],
                                'weight_decay': 5e-4,
                                'momentum': 0.9,
                                'optimizer': 'sgd'},
                'vgg16_1': {'batch_size': 16,
                            'num_epoch': 5,
                            'lr': 0.1,
                            'lr_type': 'multistep',
                            'decay_rate': 0.1,
                            'decay_epochs': [100, 200],
                            'weight_decay': 5e-4,
                            'momentum': 0.9,
                            'optimizer': 'sgd'},
                'vgg16_4': {'batch_size': 16,
                            'num_epoch': 5,
                            'lr': 0.1,
                            'lr_type': 'multistep',
                            'decay_rate': 0.1,
                            'decay_epochs': [100, 200],
                            'weight_decay': 5e-4,
                            'momentum': 0.9,
                            'optimizer': 'sgd'},
                'mobilenet_v2_1': {'batch_size': 16,
                                   'num_epoch': 5,
                                   'lr': 0.1,
                                   'lr_type': 'multistep',
                                   'decay_rate': 0.1,
                                   'decay_epochs': [100, 200],
                                   'weight_decay': 5e-4,
                                   'momentum': 0.9,
                                   'optimizer': 'sgd'},
                'mobilenet_v2_4': {'batch_size': 16,
                                   'num_epoch': 5,
                                   'lr': 0.1,
                                   'lr_type': 'multistep',
                                   'decay_rate': 0.1,
                                   'decay_epochs': [100, 200],
                                   'weight_decay': 5e-4,
                                   'momentum': 0.9,
                                   'optimizer': 'sgd'}
            },
            'tiny_imagenet': {
                'vgg16_1': {'batch_size': 50,
                            'num_epoch': 5,
                            'lr': 0.01,
                            'lr_type': 'exp',
                            'decay_rate': 0.998,
                            'decay_epochs': [1],
                            'weight_decay': 1e-4,
                            'momentum': 0.5,
                            'optimizer': 'sgd'},
                'vgg16_4': {'batch_size': 50,
                            'num_epoch': 5,
                            'lr': 0.01,
                            'lr_type': 'exp',
                            'decay_rate': 0.998,
                            'decay_epochs': [1],
                            'weight_decay': 1e-4,
                            'momentum': 0.5,
                            'optimizer': 'sgd'},
                'resnet110_1': {'batch_size': 50,
                                'num_epoch': 5,
                                'lr': 0.01,
                                'lr_type': 'exp',
                                'decay_rate': 0.998,
                                'decay_epochs': [1],
                                'weight_decay': 1e-4,
                                'momentum': 0.5,
                                'optimizer': 'sgd'},
                'resnet110_4': {'batch_size': 50,
                                'num_epoch': 5,
                                'lr': 0.01,
                                'lr_type': 'exp',
                                'decay_rate': 0.998,
                                'decay_epochs': [1],
                                'weight_decay': 1e-4,
                                'momentum': 0.5,
                                'optimizer': 'sgd'},
                'mobilenet_v2_1': {'batch_size': 50,
                                   'num_epoch': 5,
                                   'lr': 0.01,
                                   'lr_type': 'exp',
                                   'decay_rate': 0.998,
                                   'decay_epochs': [1],
                                   'weight_decay': 1e-4,
                                   'momentum': 0.5,
                                   'optimizer': 'sgd'},
                'mobilenet_v2_4': {'batch_size': 50,
                                   'num_epoch': 5,
                                   'lr': 0.01,
                                   'lr_type': 'exp',
                                   'decay_rate': 0.998,
                                   'decay_epochs': [1],
                                   'weight_decay': 1e-4,
                                   'momentum': 0.5,
                                   'optimizer': 'sgd'}
            }
        }
        self.model_params = {
            'cifar10': {
                'msdnet24_1': {'base': 6,
                               'step': 6,
                               'num_scales': 3,
                               'step_mode': 'even',
                               'num_channels': 16,
                               'growth_rate': 6,
                               'growth_factor': [1, 2, 4],
                               'prune': 'max',
                               'bn_factor': [1, 2, 4],
                               'bottleneck': True,
                               'compression': 0.5,
                               'num_blocks': 1,
                               'reduction': 0.5},
                'msdnet24_4': {'base': 6,
                               'step': 6,
                               'num_scales': 3,
                               'step_mode': 'even',
                               'num_channels': 16,
                               'growth_rate': 6,
                               'growth_factor': [1, 2, 4],
                               'prune': 'max',
                               'bn_factor': [1, 2, 4],
                               'bottleneck': True,
                               'compression': 0.5,
                               'num_blocks': 4,
                               'reduction': 0.5},
                'resnet110_1': {'ee_layer_locations': [],
                                'ee_num_conv_layers': [],
                                'num_blocks': 1},
                'resnet110_4': {'ee_layer_locations': [30, 38, 46],
                                'ee_num_conv_layers': [3, 3, 3],
                                'num_blocks': 4},
                'vgg16_1': {'ee_layer_locations': [],
                            'ee_num_conv_layers': [],
                            'num_blocks': 1},
                'vgg16_4': {'ee_layer_locations': [8],
                            'ee_num_conv_layers': [3],
                            'num_blocks': 4},
                'mobilenet_v2_1': {'ee_layer_locations': [],
                                   'ee_num_conv_layers': [],
                                   'num_blocks': 1},
                'mobilenet_v2_4': {'ee_layer_locations': [6, 8],
                                   'ee_num_conv_layers': [3, 3],
                                   'num_blocks': 4},
            },
            'cifar100': {
                'msdnet24_1': {'base': 6,
                               'step': 6,
                               'num_scales': 3,
                               'step_mode': 'even',
                               'num_channels': 16,
                               'growth_rate': 6,
                               'growth_factor': [1, 2, 4],
                               'prune': 'max',
                               'bn_factor': [1, 2, 4],
                               'bottleneck': True,
                               'compression': 0.5,
                               'num_blocks': 1,
                               'reduction': 0.5},
                'msdnet24_4': {'base': 6,
                               'step': 6,
                               'num_scales': 3,
                               'step_mode': 'even',
                               'num_channels': 16,
                               'growth_rate': 6,
                               'growth_factor': [1, 2, 4],
                               'prune': 'max',
                               'bn_factor': [1, 2, 4],
                               'bottleneck': True,
                               'compression': 0.5,
                               'num_blocks': 4,
                               'reduction': 0.5},
                'resnet110_1': {'ee_layer_locations': [],
                                'ee_num_conv_layers': [],
                                'num_blocks': 1},
                'resnet110_4': {'ee_layer_locations': [30, 38, 46],
                                'ee_num_conv_layers': [3, 3, 3],
                                'num_blocks': 4},
                'vgg16_1': {'ee_layer_locations': [],
                            'ee_num_conv_layers': [],
                            'num_blocks': 1},
                'vgg16_4': {'ee_layer_locations': [8],
                            'ee_num_conv_layers': [3],
                            'num_blocks': 4},
                'mobilenet_v2_1': {'ee_layer_locations': [],
                                   'ee_num_conv_layers': [],
                                   'num_blocks': 1},
                'mobilenet_v2_4': {'ee_layer_locations': [6, 8],
                                   'ee_num_conv_layers': [3, 3],
                                   'num_blocks': 4}
            },
            'tiny_imagenet': {
                'vgg16_1': {'ee_layer_locations': [],
                            'ee_num_conv_layers': [],
                            'num_blocks': 1},
                'vgg16_4': {'ee_layer_locations': [8],
                            'ee_num_conv_layers': [3],
                            'num_blocks': 4},
                'resnet110_1': {'ee_layer_locations': [],
                                'ee_num_conv_layers': [],
                                'num_blocks': 1},
                'resnet110_4': {'ee_layer_locations': [30, 38, 46],
                                'ee_num_conv_layers': [3, 3, 3],
                                'num_blocks': 4},
                'mobilenet_v2_1': {'ee_layer_locations': [],
                                   'ee_num_conv_layers': [],
                                   'num_blocks': 1},
                'mobilenet_v2_4': {'ee_layer_locations': [6, 8],
                                   'ee_num_conv_layers': [3, 3],
                                   'num_blocks': 4}
            }
        }
